#! /usr/bin/env bash
set -ue -o pipefail

owd="$(pwd)"
homepath=~/Nix/home-manager
gitrepo=Githver/sputnix-home
hostname="$(hostname)"

function main {

    if command -v home-manager > /dev/null >& 2; then
        echo "home-manager is already installed"
        exit 2
    fi

    if [ ! -f $homepath ]; then
        create-paths
    fi
    # Open the flake in the editor to change variables to their correct values
    # nix shell nixpkgs#helix --command hx "$homepath"/flake.nix
    # nix shell nixpkgs#helix --command hx "$homepath"/hosts/"$hostname"/info.nix
    install
    check-nixetc

}

function create-paths {
    # Create the `Nix` directories
    mkdir -p "$homepath"
    # Clone the repository and remove the git repo
    nix shell nixpkgs#git --command git clone https://github.com/"$gitrepo".git "$homepath"
    rm -rf "$homepath"/.git
    # Creates a symbolic link in the home-manager directory
    mkdir ~/.config/home-manager
    # Creates a symbolic link for shorter commands
    ln -s "$homepath"/flake.nix ~/.config/home-manager
    # Create the `hosts` directory in the home manager repo
    mkdir -p "$homepath"/hosts/"$hostname"
    # Copy the default file from the sample host.
    cp "$homepath"/hosts/sample-host/default.nix "$homepath"/hosts/"$hostname"/default.nix
    # Create a file with the host name of the current machine
    nix eval --impure --expr 'builtins.currentSystem' > "$homepath"/hosts/"$hostname"/arch.nix
    sed -i "s/your_username/$USER/" "$homepath"/flake.nix
}

function install {
    # Install and run home-manager
    nix shell nixpkgs#home-manager --command home-manager switch
    if [ $? != 0 ]; then
        echo '
            The home-manager build failed. This can be for a number of reasons.
            Try updating the "lock" file with `nix flake update` and try again.
        '
        exit 1
    fi
    # Initialize the Home-manager git repository
    cd "$homepath"
    git init
    git add -A
    git commit -m 'initial commit'
    # Go back home
    cd "$owd"
}

function check-nixetc {
    if [ -f /etc/nixos/flake.lock ]; then
        echo "moving the NixOS config from /etc/nixos into $USER/Nix/nixos-config"
        cp -r /etc/nixos ~/Nix/nixos-config
        sudo rm -rf /etc/nixos/*
        sudo ln -s "$USER"/Nix/nixos-config/flake.nix /etc/nixos/flake.nix
    else
        echo "/etc/nixos is already empty"
    fi
}

main "$@"
